twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        my_config:
            toolbar: full
            jquery: true
            input_sync: true
            language: fr
            extraPlugins: "templates"
