# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"
    twig:
        mode:             legacy

    filter_sets:
        cache: ~
        # les derniers articles
        # nom du filtre que l'ont va récupérer dans la vue 
        dernier_article:
        # ajustement de la qualité
            quality: 100
        # sélection du filtre que l'ont va appliquer
            filters:
        # je créer un filtre "thumbnail" de taille 300*300 et je lui applique un mode "outbound"
        # to crop the image when the size ratio of the input differs
                thumbnail: { size: [300, 300], mode: outbound }

        # nom du filtre  "slider"
        slider:
            quality: 100
            filters:
        # j'utilise un filtre fixe
                    fixed:
        # je lui applique une taille de 1200*500
                        width: 750
                        height: 750

        #dossier de la semaine
        dossier_semaine:
            quality: 100
            filters:
                    fixed:
                        width: 500
                        height: 500

        #dossier de la semaine sidebar
        side_bar:
            quality: 100
            filters:
                    fixed:
                        width: 200
                        height: 200
                    
        #Zoom
        zoom:
            quality: 90
            filters:
                    fixed:
                        width: 400
                        height: 400
        #logo
        logo:
            quality: 90
            filters:
                    fixed:
                        width: 150
                        height: 150
        #configuration des articles card
        card:
            quality: 90
            filters:
                    fixed:
                        width: 300
                        height: 300
        #CONFIGURATION DE LA PAGE article/index.html.twig
        article:
            quality: 90
            filters:
                    fixed:
                        width: 900
                        height: 300
        #avatar
        avatar:
            quality: 90
            filters:
                    fixed:
                        width: 100
                        height: 100
        
        #video
        video:
            quality: 100
            filters:
                fixed:
                    width: 900
                    height: 300
        
        #background
        my_background:
                quality: 100
                filters:
                    fixed:
                        width: 900
                        height: 750



        
        



        

