symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    #durée de validité d'une demande de réinitialisation de mot de passe 
    lifetime: 3600
    #durée avant qu'un utilisateur puisse demander une autre demande de réinitialisation
    throttle_limit: 3600
    #ttoyeur de mot de passe de réinitialisation qui gère les demandes de mot de passe de réinitialisation expirées qui peuvent avoir été laissées en persistance.
    enable_garbage_collection: true
