twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        categoryService: "@App\\Service\\CategorieService"
        articleController: "@App\\Controller\\ArticleController"
when@test:
    twig:
        strict_variables: true
