vich_uploader:
    db_driver: orm # or mongodb or phpcr - default db driver
    metadata:
        type: attribute

    #mapping images des articles
    mappings:
        articles_images:
            uri_prefix: "%articles_images%"
            upload_destination: "%kernel.project_dir%/public%articles_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
        #mapping images des avatar du profil utilisateurs
        images:
            uri_prefix: "%images%"
            upload_destination: "%kernel.project_dir%/public%images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        #mapping des video 
        video:
            uri_prefix: "%video%"
            upload_destination: "%kernel.project_dir%/public%video%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
