vich_uploader:
    db_driver: orm

    mappings:
        articles_images:
            uri_prefix: '%articles_images%'
            upload_destination: "%kernel.project_dir%/public%articles_images%"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: false
