name: symfony
on: [ push, pull_request ]
jobs:
  code-quality:
    name: PHPStan & PHP-CS-Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.1' ]
      fail-fast: false
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v2

      - name: Composer Install
        run: composer install --ansi --prefer-dist --no-interaction --no-progress
      
      - name: Composer Install PHP-CS-Fixer
        run: cd tools/php-cs-fixer && composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Run Code Quality checks
        run: composer check-quality